DROP TABLE IF EXISTS APPLICANT_TABLE;

CREATE TABLE APPLICANT_TABLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  applicant_first_name VARCHAR(250) NOT NULL,
  applicant_last_name VARCHAR(250) NOT NULL,
  company_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  salary INT
);